name: 1.0$(rev:.r)

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'amazonlinux2'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
  displayName: 'Install Lambda Layer Dependencies'

- script: |
    python main.py
